image:
  - Visual Studio 2017
clone_folder: c:\project\source
build_script:
- cmd: >-
    mkdir build
    cd build
    cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=8.1 ..
    cmake --build . --config "Debug"
